-- Seed: one pre-approved test restaurant account, for QA of the new
-- signup/login flow without waiting on the (not-yet-built) admin
-- approval screen.
--
-- Login:    test@anydrop.com
-- Password: test
--
-- Password hash below is bcrypt ($2b$, 12 rounds) for the literal
-- string "test" — PHP's password_verify() accepts $2b$/$2a$/$2y$ bcrypt
-- hashes interchangeably, so this verifies correctly against
-- restaurant-login.php even though it wasn't generated by PHP's own
-- password_hash(). Deliberately status='approved' so it skips the
-- pending-approval gate entirely — this is a test/QA account, not
-- something that should exist in production data.
--
-- Idempotent: safe to re-run, updates the existing row instead of
-- erroring on the UNIQUE owner_email constraint.

INSERT INTO restaurants (
    name, owner_name, owner_mobile, owner_email, password_hash,
    address, is_veg_only, opening_time, closing_time, working_days,
    status, operational_status, commission_percent
) VALUES (
    'Test Restaurant', 'Test Owner', '9999999999', 'test@anydrop.com',
    '$2b$12$t9Tyo/guan4zeTCEDWyo/e6rK0tZHk.rf9apAcVDbCh67MXHPFBUa',
    'Test Address, QA City', 0, '09:00:00', '23:00:00', '1,2,3,4,5,6,7',
    'approved', 'open', 15.00
)
ON DUPLICATE KEY UPDATE
    password_hash = VALUES(password_hash),
    status = 'approved',
    operational_status = 'open';
